---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bloon.
--- DateTime: 7/2/2020 12:06 PM
---

PlayState = Class{__include = BaseState}

function PlayState:enter(params)
    self.player = params.player
    self.monitor = params.monitor
    self.obstacles = params.obstacles
    self.tiles = params.tiles
    self.ghosts = params.ghosts
end

function PlayState:update(dt)
    self.player:update(dt)
    self.monitor:update(dt)

    if self.player:collides(self.monitor) and self.monitor.isVisible then
        self.player.acquiredMonitor = true
        self.monitor.isVisible = false
        gSounds['monitorPickup']:play()

        for _, ghost in pairs(self.ghosts) do
            ghost:update(true)
        end
    end

    for _, ghost in pairs(self.ghosts) do
        if ghost.isVisible and self.player:collides(ghost) then
            ghost:update(false)
        end
    end

    self.player:update(dt)
    self.monitor:update(dt)
end

function PlayState:render()
    self.monitor:render()

    for _, obstacle in pairs(self.obstacles) do
        obstacle:render()
    end
    for _, tile in pairs(self.tiles) do
        tile:render()
    end
    for _, ghost in pairs(self.ghosts) do
        ghost:render()
    end

    self.player:render()
end

function PlayState:exit() end
