---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bloon.
--- DateTime: 7/2/2020 11:59 AM
---

-- push is a library that will allow us to draw our game at a virtual
-- resolution, instead of however large our window is; used to provide
-- a more retro aesthetic
--
-- https://github.com/Ulydev/push
push = require 'lib/push'

-- the "Class" library we're using will allow us to represent anything in
-- our game as code, rather than keeping track of many disparate variables and
-- methods
--
-- https://github.com/vrld/hump/blob/master/class.lua
Class = require 'lib/class'

-- utility functions, mainly for splitting our sprite sheet into various Quads
require 'src/Utils'

-- a basic StateMachine class which will allow us to transition to and from
-- game states smoothly and avoid monolithic code in one file
require 'src/StateMachine'

require 'src/Player'
require 'src/Obstacle'
require 'src/Tile'
require 'src/Ghost'
require 'src/Monitor'

-- each of the individual states our game can be in at once; each state has
-- its own update and render methods that can be called by our state machine
-- each frame, to avoid bulky code in main.lua

require 'src/states/BaseState'
require 'src/states/PlayState'
require 'src/states/MenuState'
require 'src/states/InfoState'
require 'src/states/GhostInfoState'

gSounds = {
    ['synne1'] = love.audio.newSource("sounds/Wergelandsveien7.wav", "static"),
    ['synne2'] = love.audio.newSource("sounds/Wergelandsveien73.wav", "static"),
    ['background'] = love.audio.newSource("sounds/hurryup.wav", "stream"),
    ['monitorPickup'] = love.audio.newSource("sounds/Pickup_Coin.wav", "static"),
    ['jump'] = love.audio.newSource("sounds/jump.wav"),
}

gGraphics = {
    ['menu'] = love.graphics.newImage('graphics/menu.png'),
    ['logo'] = love.graphics.newImage('graphics/logo.png'),
    ['background'] = love.graphics.newImage('graphics/background.png'),
    ['ground'] = love.graphics.newImage('graphics/ground.png'),
    ['monitor'] = love.graphics.newImage('graphics/airthings.png'),
    ['obstacles'] = {
        ['bookcase'] = love.graphics.newImage('graphics/furni2.png'),
        ['longTable'] = love.graphics.newImage('graphics/furni5.png'),
        ['diningTable'] = love.graphics.newImage('graphics/furni6.png'),
        ['lamp'] = love.graphics.newImage('graphics/furni7.png'),
        ['mirror'] = love.graphics.newImage('graphics/furni8.png'),
    },
    ['tile'] = love.graphics.newImage('graphics/tile.png'),
    ['player'] = {
        ['left'] = love.graphics.newImage('graphics/player/hero2.png'),
        ['right'] = love.graphics.newImage('graphics/player/hero1.png'),
        ['radon_left'] = love.graphics.newImage('graphics/player/hero_radon2.png'),
        ['radon_right'] = love.graphics.newImage('graphics/player/hero_radon1.png'),
    },
    ['ghosts'] = {
        ['adam'] = love.graphics.newImage('graphics/Radon1.png'),
        ['bob'] = love.graphics.newImage('graphics/Radon2.png'),
        ['carl'] = love.graphics.newImage('graphics/Radon3.png'),
    }
}

gFonts = {
    ['big'] = love.graphics.newFont('fonts/font.ttf', 32),
    ['medium'] = love.graphics.newFont('fonts/font.ttf', 16),
    ['small'] = love.graphics.newFont('fonts/font.ttf', 8),
}
