---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bloon.
--- DateTime: 7/2/2020 12:08 PM
---

Monitor = Class{}


function Monitor:init(img, x)
    self.image = img
    self.width = img:getWidth()
    self.height = img:getHeight()
    self.x = x
    self.isVisible = true
end

function Monitor:collides(target)
    -- first, check to see if the left edge of either is farther to the right
    -- than the right edge of the other
    if self.x > target.x + target.width or target.x > self.x + self.width then
        return false
    end

    -- then check to see if the bottom edge of either is higher than the top
    -- edge of the other
    if self.y > target.y + target.height or target.y > self.y + self.height then
        return false
    end

    -- if the above aren't true, they're overlapping
    return true
end

function Monitor:update(dt)

end

function Monitor:render()
    love.graphics.draw(self.image, self.x, VIRTUAL_HEIGHT - GROUND_HEIGHT - self.height, 0)
end
