---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bloon.
--- DateTime: 7/2/2020 12:08 PM
---

Monitor = Class{}

local count = 0


function Monitor:init(img, x, y)
    self.image = img
    self.width = img:getWidth()
    self.height = img:getHeight()
    self.x = x
    self.y = y
    self.isVisible = true
end

function Monitor:update(dt)
end

function Monitor:render()
    if self.isVisible then
        love.graphics.draw(self.image, self.x, self.y, 0)
    end
end
