---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bloon.
--- DateTime: 7/2/2020 12:08 PM
---

Obstacle = Class{}

function Obstacle:init(img, x, dyFromGround)
    self.image = img
    self.width = img:getWidth()
    self.height = img:getHeight()
    self.x = x

    local dy = dyFromGround or 0
    self.y = VIRTUAL_HEIGHT - GROUND_HEIGHT - self.height - dy
end

function Obstacle:update(dt)

end

function Obstacle:render()
    love.graphics.draw(self.image, self.x, self.y)
end
