---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bloon.
--- DateTime: 7/2/2020 12:08 PM
---

Obstacle = Class{}

local obstacleScaleFactor = 0.5

function Obstacle:init(img, x)
    self.image = img
    self.width = img:getWidth()
    self.height = img:getHeight() * obstacleScaleFactor
    self.x = x
    self.isVisible = true
end

function Obstacle:update(dt)

end

function Obstacle:render()
    love.graphics.draw(self.image, self.x, VIRTUAL_HEIGHT - GROUND_HEIGHT - self.height, 0, obstacleScaleFactor, obstacleScaleFactor)
end
