---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bloon.
--- DateTime: 7/2/2020 12:26 PM
---

--[[
    Given an "atlas" (a texture with multiple sprites), as well as a
    width and a height for the tiles therein, split the texture into
    all of the quads by simply dividing it evenly.
]]
function GenerateQuads(atlas, tileWidth, tileHeight)
    local sheetWidth = atlas:getWidth() / tileWidth
    local sheetHeight = atlas:getHeight() / tileHeight

    local sheetCounter = 1
    local spriteSheet = {}

    for y = 0, sheetHeight - 1 do
        for x = 0, sheetWidth - 1 do
            spriteSheet[sheetCounter] =
            love.graphics.newQuad(x * tileWidth, y * tileHeight, tileWidth,
                    tileHeight, atlas:getDimensions())
            sheetCounter = sheetCounter + 1
        end
    end

    return spriteSheet
end

--[[
    Utility function for slicing tables, a la Python.

    https://stackoverflow.com/questions/24821045/does-lua-have-something-like-pythons-slice
]]
function table.slice(tbl, first, last, step)
    local sliced = {}

    for i = first or 1, last or #tbl, step or 1 do
        sliced[#sliced+1] = tbl[i]
    end

    return sliced
end

function GeneratePlayerQuads(atlas)
    return {
        ['down'] = table.slice(GenerateQuads(atlas, 32, 32), 1, 12),
        ['left'] = table.slice(GenerateQuads(atlas, 32, 32), 13, 24),
        ['right'] = table.slice(GenerateQuads(atlas, 32, 32), 25, 36),
        ['up'] = table.slice(GenerateQuads(atlas, 32, 32), 37, 48)
    }
end
